### ISSUE TITLE
Clarification p:tee needed (remove p:tee)

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-steps#101]
`p:tee` has sequence source and result ports, but only a single href option to write a document to. What happens when there are multiple documents on the source port?

**Comment by eriksiegel** [comment]
My preferred solution would be to simply store only the *first* document appearing on the source port.

**Comment by gimsieke** [comment]
Alternatively, interpret `href` as a directory if there are multiple documents and store the individual documents below this directory, with implementation-dependent names (for ex., `1.xml`, `2.json`, …; or use the filename parts of their base URIs, if unique; or disambiguate by prepending a sequence number; etc.). 
I see some use in storing them all.

**Comment by eriksiegel** [comment]
@gimsieke I have no use-case for more-than-one-doc but I can see your point. What would be your preferred algorithm for the filenames and what do the implementers think about this?

**Comment by gimsieke** [comment]
The algorithm may be implementation-defined, but if we were to suggest something I’d say: Use the filename part of the base URI, possibly disambiguated by prepending them with a sequence number and a separator like `_`.
In contrast to what I said above, it shouldn’t depend on the number of input documents whether `href` is interpreted as a directory. It’s probably better to treat it as a directory if and only if it ends with a slash. This means we need to raise a dynamic error if there are multiple source documents and `href` doesn’t end in `/`.

**Comment by Conal-Tuohy** [comment]
Alternatively, `p:tee` could have non-sequence ports, and a programmer who wanted to use it with a sequence could wrap it in a `p:for-each`, and compute a distinct `@href` dynamically within the `p:for-each`.

**Comment by xml-project** [comment]
No opinion here, but two comment:
(1) What do we say about option `serialization` in port source has a mixed content (text, json, xml ...)?
(2) If we want an algorithm for calculating the filename, I think it should be controllable by pipeline authors via additional options.

**Comment by eriksiegel** [comment]
Ok, after some thinking, my opinion:

1. I asked for `p:tee` because it is such a marvelous debugging aid
1. There is only one option to pass in serialization parameters
1. Given the above, lets keep thing simple: First document passing through is serialized. `href` is not a directory name but a filename
1. If you really need multiple documents, wrap it in a `p:for-each` as @Conal-Tuohy writes

**Comment by ndw** [comment]
Consensus: change p:store and other steps to support outputting the input document and the URI; remove p:tee. (This issue is now about removing p:tee). See also #106
