### ISSUE TITLE
Change p:store and friends to have multiple output ports

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#106]
Proposal: steps that have a port that returns the URI, should be
     changed such that they have a primary output port called ‘result’
     that returns the input document and a secondary port called
     ‘result-uri’ that returns the URI.

**Comment by xml-project** [comment]
Fixed for p:store with PR # #148 Now looking for "friends".

**Comment by xml-project** [comment]
Any hint what "friends" are?

**Comment by gimsieke** [comment]
p:xsl-formatter and likewise p:css-formatter come to my mind

**Comment by xml-project** [comment]
@gimsieke Could you explain this please. To my reading these to steps produce documents on their result port. What did I miss?

**Comment by ndw** [comment]
They used to produce the URI on their output port, like store.

**Comment by xml-project** [comment]
So? Can we close this?

**Comment by ndw** [comment]
Ah yes, I see what you mean. They aren't really the same. Given that they *don't* write to disk anymore, there's no URI for them to return.

Yes, I think you can close this. We can always open another issue if we think of a case we missed.
