### ISSUE TITLE
Clarify p:archive and p:unarchive

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#116]
1. It's an error if two documents with the same base URI appear on the source port
2. It is an error if a document without a base URI appears on the source port
3. It is an error if more than one document appears on the archive port
4. ...

**Comment by eriksiegel** [comment]
* unarchive should no longer do any manifest generation
* filters must be string*

**Comment by eriksiegel** [comment]
As of 20190620:

* No content directly in the manifest
* Serialization document property is used

**Comment by eriksiegel** [comment]
Closed with one thing to discuss left: #155

**Comment by eriksiegel** [comment]
Looking at what is already done, I think this one can be closed.
