### ISSUE TITLE
p:delete deleting the document element

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#122]
In the light of #100 and #93 I propose to adapt this change to p:delete too: If the resulting document is a document node containing just one text node, the content-type should switch to "text/plain" and the serialization entry in the document properties should be deleted.

**Comment by ndw** [comment]
:+1

**Comment by xml-project** [comment]
Another point: We do not say currently, what is supposed to happen, if match ="/" is used. This was also not defined in 1.0, so both processors deliver different results.
Proposal: It is an error to match the document node. (XC0023)
