### ISSUE TITLE
add content-type to c:file and to the result of p:file-info

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-steps#128]
@xml-project [stumbled across `@content-types` on `c:file`](https://github.com/xproc/3.0-steps/pull/127#pullrequestreview-250191350). It was introduced in https://github.com/xproc/3.0-specification/commit/831031cf8302b97b5d99a127b07c1e69847310d4 in an attempt to resolve https://github.com/xproc/3.0-specification/issues/405. 

It should be renamed `@content-type`, but it should also be mentioned in [`p:file-info`](http://spec.xproc.org/master/head/file/#c.file-info) as a possible attribute for `c:file` result elements (maybe make it implementation-defined whether it will be returned or for which URI schemes; or simply say that if this information is available or can be reasonably inferred, implementations should add this attribute.

I added the [info result attributes](https://github.com/xproc/3.0-steps/commit/3618dc1c3c6746a392bdfa0b084d2acbff48fac4#diff-240748684ef21d0af7e83fd762195207R849) to core30.rnc in the 3.0-steps repo. Maybe its definition should be extended to `size.attr | readable.attr | writable.attr | last-modified.attr | hidden.attr | content-type.attr`. Or since it is irrelevant to `c:other` and `c:directory`, we could simply re-introduce the now correctly named `@content-type` on `c:file`.

I think @ndw is planning to outsource the core30 schema (and maybe other resouces) to a shared repo so that we don’t have to synchronize them manually.

**Comment by eriksiegel** [comment]
Spec needs an update

**Comment by eriksiegel** [comment]
Core schema must be changed and some prose

**Comment by xml-project** [comment]
Think this is fixed with #128. Close?
