### ISSUE TITLE
The http-request step needs to be updated

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#13]
# The http-request response needs to be updated 

>This is an aggregation of the discussion on "The http-request response needs to be updated" ([Issue 170 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/170))

**Opened by: ndw on 2015-06-10, 10:21h**

## ndw said on 2015-06-10, 10:21h:

The current result is a c:response element with embedded possibly base64 encoded c:body element(s). If the response is multipart, we should probably now produce a sequence. Put the headers in the document-properties? 

	On 2015-10-07, 14:27h: ndw added this to the XProc 2.0 LC milestone.

**Comment by ndw** [comment]
Notes from the 05 Feb 2019 workshop:

* JSON document as input? Yes, of course. Recursive maps.
* Allow the 11 current attributes on c:request as options on p:http-request
* Error if you specify an option in both places and they’re inconsistent
* Review the http-request work that Adam did for EXPath
* A simple body that isn’t a c:request is a single c:body
* A simple body that is a JSON object with a “http-request”
  key with the value “request” is a complex request.
* If the input is JSON, a detailed response is JSON
* If the input is XML, a detailed response is XML
* Change the ‘detailed’ option to take JSON/XML as values
* Geert observes that he likes the work in EXPath except for
  the fact that the response is always a map, even in the simple
  case.
* “Where do we say that for URI schemes (such as file: and ftp:)
  where a content type is not provided by the underlying request,
  the content type is implementation-dependent?”
  * If we don’t, we should.
  * Use the same algorithm as p:load/p:document
* “The requirement to process the external subset comes from
  p:load, we probably don't want to impose that on all
  p:http-request calls. Need a way to control it?”
  * No.

**Comment by xml-project** [comment]
Yes, that is the way I was thinking along. (With the difference of having a third map `parameters` on `p:http-request` for the options on `c:request`).

But one question:

> Now simple GET requests don't require any c:request element. We can say that the source input is ignored for GET, that means authors don't even have to worry about how the input port is
bound on GET.

How do you do that. Input ports have to be connected, so you have to supply a `p:empty` for "GET" or "DELETE". Failing to do so is a static error.
What did I miss?

> but I'm a whole lot more concerned about having a step that's easy to use.
IMHO that should be our number one priority.

**Comment by Conal-Tuohy** [comment]
One thing that concerns me about mapping multipart messages to an XProc sequence is that it doesn't seem to allow for nesting. A multipart MIME message may contain parts which are themselves multiparts. 

Also I'm not sure how the multipart=sequence approach would deal with the different types of multipart message (e.g. multipart/mixed, multipart/alternative, etc). Would it still allow the different subtypes of multipart to be distinguished? This is where EXPath's approach is superior (if I understand it correctly).

**Comment by xml-project** [comment]
Conal-Tuohy said:
> which is why I also dislike the idea of a "white-list" of HTTP methods

👍

**Comment by Gertone** [comment]
Well, the EXPath approach does cover the whole complexity. It is good, but it also adds a lot of complexity to the simple cases. That is one issue to cover.
Nested maps could allow for the nesting potentially required actually.
About the white-listing.. I brought it up here because #42 is labelled "consensus-reached". The way I see that: it is a mandatory set of methods an implementer is required to implement to be compliant. That is not necessarily as restrictive as you seem to believe

**Comment by Conal-Tuohy** [comment]
Yeah, thi sis a bit off-topic here, but just quickly: it's not that I think a white-list is _in itself_ restrictive, but it _does" validate an implementation which _is_ restrictive. I don't believe those restrictions are necessary; I don't believe that it's significantly more difficult for an XProc implementer to support _any and all_ HTTP methods than it is to just implement the most popular 3 or 4. I think, though, that  if the spec mandates a certain restricted set of methods, it will, in practical terms, have the effect of restricting implementations to those methods.

**Comment by Conal-Tuohy** [comment]
Regarding the extra complexity of EXPath's approach, can we discuss this with the aid of some example? 
It seems to me that the common case, when I just want to access the actual entity returned by the HTTP server, in the step subsequent to the `http-request`, I could just use an XPath expression like `.?body` -- is it more complicated than that?

**Comment by xml-project** [comment]
On editors call on 2019-10-03 we came up with this idea make response processing easier: The step get an option `accept-content-type` which take the same mime type syntax as `content-types`. If `p:http-request` returns result which does not match one of the listed content-types, an error is raised.
So: I you do not want a multi-part response you could use this option to make sure an error is raised, if the request return one. Or: If you know, that no multi-part response will result from a request, you can write a pipeline just dealing with a simple response without additional checks.

**Comment by xml-project** [comment]
See pr #330

**Comment by xml-project** [comment]
Addressed in pr #330 

Closed as suggested in https://github.com/xproc/3.0-steps/pull/330#issuecomment-571564105
