### ISSUE TITLE
Matching the document node

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#130]
While implementing some steps I observed that the current specs has a variety concerning matching the document node for "replacing steps". Here is my results:

- "p:hash": No ruling for matching the document node.
- "p: replace": Error XC0023
- "p: string-replace": No ruling.
- "p:unwrap": Error XC0023
- "p:uuid": No Ruling.

As we need a ruling for the uncovered cases, two solutions came up to me:

1. It is an error in these cases too.
2. If the document node is matched, the result is a text document containing the replacing string.

Which one do you find more natural?

**Comment by gimsieke** [comment]
I prefer creating text documents throughout

**Comment by xml-project** [comment]
> I prefer creating text documents throughout
Even for those, which currently supposed to raise an error?

**Comment by gimsieke** [comment]
Yes

**Comment by ndw** [comment]
Fine by me.

**Comment by xml-project** [comment]
Sorry, for the `p:unwrap` case, I do not see how to have the text document result requested by @gimsieke . If the document node is matched (currently an error) I would expect, that the result is a new document node having the same children as the source. So matching the document node is senseless, but that does not make it an error.
However: How to make a text document? (Mind that source doesn't accept only xml and html).
What did I miss?
