### ISSUE TITLE
p:unescape-markup

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#137]
p:unescape-markup uses the concept of a document element, but as we switched to XDM a document-node now can have multiple element children.
If we want to keep p:unescape-mark the inverse of p:escape-markup, we have to do something about this.

@gimsieke commented on this:

> Can we keep the sentence “When the string value is parsed, the original document element is preserved so that the result will be well-formed XML even if the content consists of multiple, sibling elements.” if there can be multiple top-level elements?

**Comment by xml-project** [comment]
@gimsieke said:

> I propose that we delete the paragraph “When the string value is parsed […] multiple, sibling elements.” since we abandoned the concept of a single “document element” and because the result, when serialized, will not be well-formed if the input already contained multiple top-level elements.

**Comment by xml-project** [comment]
The specs say on "p:unescape-markup": No document properties are preserved.

(1) I find it difficult to understand why: One might understand this as a special kind of "p:insert" and p:insert preserves all document properties.

(2) p:unescape-markup is explained as inverse to p:escape-markup: As the latter preserves document properties I would expect this for the former.

Is this an oversight or is there some reason I failed to see?

**Comment by eriksiegel** [comment]
This might be just a mistake... Your reasoning certainly points in that direction. I have no objections.

**Comment by ndw** [comment]
Consensus on 20 June, it is an error if the input document has multiple top-level elements. As a general rule, steps that depend on the top level element should raise an error if there are multiple top-level elements.
