### ISSUE TITLE
 p:www-form-urldecode and  p:www-form-urlencode

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#139]
Could someone please have a look at these two steps. Using an XML document seems a bit odd to me, given we have now text documents and JSON documents. Doesn't it?

**Comment by Conal-Tuohy** [comment]
They should be replaced with xpath functions, in my view

**Comment by Conal-Tuohy** [comment]
There was some relevant discussion in this other issue: https://github.com/xproc/3.0-steps/issues/22 where @ndw stated there was a consensus to keep the steps as steps (i.e. not convert them to functions) and to make them convert between maps and strings. 

It's worth noting though, that www-form-urlencoded data does allow for the same key to have multiple values, e.g. `foo=bar&foo=baz`, so if the form data were represented as a map, the map's values would need to be arrays (or perhaps an array of maps: `[map{'foo':'bar'}, map{'foo':'baz'}]` might be better).

**Comment by xml-project** [comment]
Sorry, somehow missed this from #22
> Further consensus on 10 June 2019; we'll leave them steps for consistency with the rest of the design in 3.0; encoding will take a map and return a string; decoding will take a string and return a map.

**Comment by Conal-Tuohy** [comment]
I presume `www-form-urldecode` will produce a JSON document consisting of a map of strings to arrays of strings? i.e. `map(xs:string, array(xs:string))`

**Comment by xml-project** [comment]
Seem #22
