### ISSUE TITLE
Proposal for a unified validation reporting language

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-steps#15]
From Mathieu’s email 2017-12-10 message:

>Hi all,

> In my company we need an XML generic format to get errors and warning from a multiple validation (schema + schematron).
We’ve been looking at existing languages like SVRL, PSVI, XSV, saxon report language but none of them exactly matches our need.
At the beginning, we thought SVRL was the best candidate, but we found it’s actually too much tied with schematron validation only.

> So we finally create an internal grammar which we call XVRL (stands for “XML Validation Report Language”).

> We discussed in Amsterdam meetup about a unifying report ports of validation steps in xproc as describe here : https://github.com/xproc/1.0-specification/issues/135 and we thought XVRL could help in this direction ?
Please find as attach file a sample and the grammar (both Relax NG and XML Schema).
If you find this is an interesting candidate I guess we could add in on github with an open source licence.

> Any comments welcome about the format itself and about its use with xproc ?

> Best regards

> Matthieu Ricaud.

> PS : do you think adding this proposal to issue https://github.com/xproc/1.0-specification/issues/135 makes sens ? or any where else (xml-dev list?)
PPS : We also made an XVRL to JSON conversion using the xpath 3.0 xml-to-json() function

[reporting.zip](https://github.com/xproc/3.0-specification/files/2093642/reporting.zip)

**Comment by AndrewSales** [comment]
Hello,
@gimsieke directed me here and after consulting @sgmlguru and @Gertone also, would like to offer to pitch in.
For reference, we also did [something along these lines](https://web.archive.org/web/20080515174945/http://www.silcn.org/) (but inadequate for these purposes) a while back.
Not wishing to tread on any toes, @gimsieke, @mricaud - but I stand ready :)

**Comment by ndw** [comment]
Yes, please, @AndrewSales 
I'd welcome a coherent proposal. I've scratched at it a bit, but haven't produced anything I'm confident about.

**Comment by ndw** [comment]
See also: https://github.com/xproc/xvrl

**Comment by gimsieke** [comment]
@hrennau suggested that we also consider supporting SHACL validation (there’s issue #8 that already mentions SHACL), and then there needs to be a bidirectional mapping (if not an outright identity for overlapping areas covered) between the XVRL vocabulary and the [SHACL Validation Report Vocabulary](https://www.w3.org/TR/shacl/#validation-report). The serialization format is then probably everything that an RDF graph can be serialized as.

**Comment by Gertone** [comment]
There is also SHEX as an alternative to SHACL. Implementations are not at the level yet that everyone is extremely happy using them, so it might be pretty early days to implement them as a step. But worth looking into of course. But if we do so, we need to give whatever comes out of https://tools.ietf.org/pdf/draft-handrews-json-schema-00.pdf at least the same attention.

**Comment by xml-project** [comment]
Is there anything more to say on this with regard to validating XML?
Close?

**Comment by gimsieke** [comment]
Further discussion should take place on https://github.com/xproc/xvrl
