### ISSUE TITLE
@href on a c:manifest/c:entry must become mandatory

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-steps#150]
Given the decisions we made on #116, the `c:entry/@href` attribute must become mandatory. At least, I don't see the meaning or possible usage of a `c:entry` *without* an `@href`.

However, where the master schema resides and therefore how this must be done is beyond my current understanding.

**Comment by ndw** [comment]
I've pushed a PR to make the href attribute required.

**Comment by eriksiegel** [comment]
This was already done (long ago)
