### ISSUE TITLE
New step: makeJSONDocument?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#160]
Now that a JSON document (as a consequence of #61) with **any** instance of XDM (not just xs:double, xs:string and xs:boolean) can be produced via p:xslt: Should we have a step producing such a JSON document without p:xslt?
Might look like this:
````
<p:make-JSON-document>
  <p:output port="result" content-type="application/json" sequence="true" />
  <p:option name="value" as="item()*" required="true" />
  <p:option name="properties" as="map(xs:QName,item()*)" />
</p:make-JSON-document>
````

**Comment by eriksiegel** [comment]
Ok. But isn't this (almost) the same as:

```xml
<p:identity>
  <p:with-input port="source">
    { value expression }
  </p:with-input>
</p:identity>
```

**Comment by xml-project** [comment]
If I am not mistaken it's not the same. "Value expression" has to be parsed along the JSON rules. Therefor it is only the same if $var contains xs:boolean, xs:double and xs:string (along with maps and arrays).
The type information for all other XDMs in $var is lost as they will be strings.
Did I miss something?

**Comment by xml-project** [comment]
@eriksiegel Of course "it depends" (TM) on what mean by "almost". ;-))

**Comment by eriksiegel** [comment]
With "almost" I meant the absence of a properties map using `p:identity`.

**Comment by Conal-Tuohy** [comment]
Would it not be possible to specify data-typed JSON using the `select` attribute of a `with-input`?
```xml
<p:identity>
  <p:with-input port="source" select="map{'date':xs:dateTime('2019-07-08T00:00:00')}">
    <p:empty/>
  </p:with-input>
</p:identity>
```

**Comment by xml-project** [comment]
@Conal-Tuohy 
I wasn't talking about an XDM in an array or a map. That would work. I was talking about a atomic XDM value, like `xs:dateTime('2019-07-08T00:00:00')` (and all the other except boolean, double and string). And:
````
<p:identity>
  <p:with-input port="source" select="xs:date('2019-07-08')">
    <p:empty/>
  </p:with-input>
</p:identity>
````
produces a text document.
An XSLT stylesheet would accept an xs:date etc.  as initial match selection, but there is no way to supply it to XSLT (except writing an XSLT that produces it and then suppling it to the original stylesheet).
Was I able to state my problem?

**Comment by Conal-Tuohy** [comment]
I would have thought
```xml
<p:identity>
  <p:with-input port="source" select="xs:date('2019-07-08')">
    <p:empty/>
  </p:with-input>
</p:identity>
```
would produce a JSON document, since `xs:date` is an atomic type, and the spec says:

> If the item is a map, array or any atomic value, a JSON document is created and content-type application/json is used.

**Comment by xml-project** [comment]
The quoted passage starts with

> Some steps like p:xslt, p:xquery etc. create a sequence of new XDM instances.

So it is for steps and not relevant here. In the section on p:with-input/@select it is explicitly stated, that a select result is a json document only in the case of map and array.

**Comment by Conal-Tuohy** [comment]
I guess the question is whether the `etc.` includes the `p:identity` step.

**Comment by xml-project** [comment]
@Conal-Tuohy sorry, but it is about what p:with-input produces and not about steps at all. The result for p:with-input/@select is clearly stated. My point has nothing to do with what a step **produces**, but what goes into a step. So your quote is not relevant imho.

**Comment by Conal-Tuohy** [comment]
I see now ... your point is that the atomic value is converted to a plain text document by `with-input`, _before_ it is passed to the `identity` step, which therefore does not ever see the atomic type. I misunderstood the point of your example.

**Comment by Conal-Tuohy** [comment]
An alternative to adding a special "makeJSONDocument" step would be to remove the rule which says that atomic XDM instances produced by a `with-input/@select` must be munged into the form of a text document before being passed into a step. That would seem to me to be a simpler solution to the issue of how to generate JSON documents other than by `xquery` and `xslt`.

**Comment by xml-project** [comment]
Close with resolution of issue #832 in the core specs.
