### ISSUE TITLE
Are we sure about p:store?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#162]
Since `p:store` never had a primary output port, any connection to it must be explicit. Changing what appears on the `result` port seems like it could be a source of frustration for users.

How about instead we leave `result` alone and add a new port `original` that is the primary output port and returns the original document. (I'm not super enthusiastic about the name "original", if anyone has a better idea...)

**Comment by xml-project** [comment]
As you might remember, I was not a big fan of this approach. But I was convinced. Changing existing pipe connection for a 1.0 pipeline once is much better then swearing for years why the primary output port of p:store is **not** called "result".

**Comment by ndw** [comment]
I guess that rings a vague bell. Ok.
