### ISSUE TITLE
Remove statement that a reference to the XSL formatter output is in the result document

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-steps#163]
When looking at #162, I remembered that we did a similar thing with [`p:xsl-formatter`](http://spec.xproc.org/master/head/paged-media/#c.xsl-formatter): Make the result port primary (by omitting `primary="false"`) and instead of returning a `c:result` document that points to the stored resource, return the actual document (in contrast to `p:store`, `p:xsl-formatter` won’t return its input; instead, it will return the result of the formatting, usually a PDF).

This is all spec’d out fine so far. There is one sentence though that is a leftover of the [1.0 spec](https://www.w3.org/TR/xproc/#c.xsl-formatter) in the new [`p:xsl-formatter`](http://spec.xproc.org/master/head/paged-media/#c.xsl-formatter) spec: 

> A reference to that result is produced on the output port.

I propose that we delete this sentence without substitution. It will be said further down the step’s spec that the formatting result appears on the result port.

**Comment by ndw** [comment]
👍

**Comment by xml-project** [comment]
👍
