### ISSUE TITLE
Include and exclude filter are mislabeled on p:directory-list

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#166]
The comment says `<!-- RegularExpression -->`. It should be "List of RegularExpression" or "RegularExpression*s*" or, perhaps, removed entirely.

**Comment by xml-project** [comment]
👍 
Since it is `xs:string*` you are right: The comment is wrong and needs to be changed. I would tend do opt for "List of Regular Expressions" and not "RegularExpression". This is because the list can be empty.
Do we need the comment after all? I think the prose has to cover this.

**Comment by ndw** [comment]
I think we can just delete it.
