### ISSUE TITLE
include/exclude filters as xs:string*

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#167]
Last year we decided, that on p:directory-list (and other steps) we wanted to have include- and exclude-filters. And we made them `xs:string*`. At the point we decided this (if I remember right) we thought of filters as "globs". As globs could have whitespace as content, we voted against space separated list of filters but decided to go for `xs:string*` (each filter as one string in a sequence).

Later then we decided do abandon the idea of globs and went for regex, but kept `xs:string*`. As regex can not contain whitespace, I am not sure our decision against space separated entries should still hold.

Consider:
````
<p:directory-list href="something" include-filter=".*\.xpl .*\.xml" />
````
will most probably return an empty sequence, because I have to write
````
<p:directory-list path=".">
   <p:with-option name="include-filter" select="('.*\.xpl', '.*\.xml')"/>
 </p:directory-list>
````
go get all files ending with ".xpl" and ".xml". (Remember that an AVT will not solve the problem because AVTs always produce single strings, not sequence of strings).

Given this, I would like to be sure that we are still happy with `xs:string*`:
Perhaps a short survey could work.
👍 = keep xs:string*
👎 = go back to a space separated string.

**Comment by gimsieke** [comment]
👍 since a regex may well contain whitespace

**Comment by Conal-Tuohy** [comment]
Personally, I think it's quite readable to just do the disjunction in the regular expression itself (effectively, use `|` as a separator rather than a space).
```xml
<p:directory-list href="something" include-filter=".*\.xpl|.*\.xml" />
```
or (semi-facetiously)
```xml
<p:directory-list href="something" include-filter=".*\.x(p|m)l" />
```

**Comment by ndw** [comment]
Yeah, I suppose @Conal-Tuohy is right. I think users will curse us everytime they write
```
<p:directory-list href="something" include-filter=".*\.xpl .*\.xml" />
```
and it doesn't do what they expect. But maybe they can learn to use `|` instead. That's certainly a huge improvement over forcing them to use the long form of the option.

**Comment by ndw** [comment]
I think we're done here.
