### ISSUE TITLE
flatten-arrays in json-join

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#181]
Does json-join need a mechanism for flattening all nested arrays, not just the top level ones?

**Comment by xml-project** [comment]
Interesting question. Do you have a use case in mind? We could make option `flatten` an `xs:token` with something like `no`, `top` and `deep`.

**Comment by ndw** [comment]
I don't have any concrete use case in mind, but I don't have a concrete use case in mind for `flatten` in the first place. Experience with other APIs suggests that if you need to flatten one level, you might sometimes need to flatten more levels.

**Comment by ndw** [comment]
I think tokens would be fine, but I think `none`, `shallow` and `deep` might be better token values.

**Comment by xml-project** [comment]
(I do not argue about the token instances): We could also replace option `flatten` with an integer option `depth`. But is there a case where I want say the first three levels of arrays flattened but not live 4-n?
Pro: Who knows what users will do and to give them more control on the steps behaviour might be an argument.

**Comment by ndw** [comment]
If you'd like. Con: it means uses will do things like 999 to mean "deep" and then we get into discussions about whether there should be a way to say "infinity". We could say it's either the tokens 'none', 'shallow' (which is the same as 1), 'deep' (which is the same as infinity), or an integer.

**Comment by xml-project** [comment]
Right.  In p:directory-list we have `max-depth" as="xs:string?" select="'1'"/>` where `unbounded` means `infinity`. I think we should adopt that, so authors don't have to remember two different ways.

**Comment by ndw** [comment]
Yes, that works for me!
