### ISSUE TITLE
Refine XC0038 "version not supported"

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#182]
Currently we use XC0038 ("version not supported") in different steps, e.g. p:xslt, p:xquery and p:validate-with-xml-schema.
I propose to have a different error for each step, so authors can write better catch pipeline, like:
````
<p:try>
  <p:xquery />
  <p:validate-with-xml-schema />
  <p:xslt />

  <p:catch code="xquery-code">
    <!-- Error message -->
  </p:catch>
  <p:catch code="validate-with-xml-schema-code>
    <!-- Error message -->
  </p:catch>
  <!-- ... -->
</p:try>
````

**Comment by ndw** [comment]
Fine by me.
