### ISSUE TITLE
Issue in signature of p:validate-with-relax-ng

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#183]
There is an issue with port `schema` defined as `content-type="text xml". 
The prose then says, that a document with media type "application/relax-ng-compact-syntax" is also accepted and triggers the compact syntax mode.

Using a document with this media type on port schema will always raise "XD0038" (unexpected media type).

Solutions:

1. We drop the special treat for this media type: If it comes in, authors have to use p:cast-content-type to make it a text document.
2. We explicitly allow documents with this media type on port `schema`.
3. We add this media type to our overall definition of "text document".

I have a slight preference for (3) because compact syntax documents could be treated as text (in text steps). But I could also life with (2). (1) would be inconvenient to authors.

**Comment by gimsieke** [comment]
I’d prefer 3, too. We can then rephrase the prose to:

> If the schema document has a “`text`” media type, which comprises “`application/relax-ng-compact-syntax`,” then it must be interpreted as a [RELAX NG Compact Syntax](http://spec.xproc.org/master/head/validation/#relaxng-compact-syntax) document for validation.

**Comment by ndw** [comment]
Seems like this is something implementors are going to have to let users customize.

I don't object to enumerating a few more types as "text".
