### ISSUE TITLE
Missing ruling in p:xslt

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#187]
In the [specs](http://spec.xproc.org/master/head/steps/#c.xslt) we say:

> Option output-base-uri sets the base output URI per XSLT 3.0 specification. If a final result tree is constructed, this URI is used to resolve a relative URI reference. If no value is supplied for output-base-uri, the base URI of the first document in the source port's sequence is used.

This is taken verbatim from the 1.0 specs, but: What happens if there is no document on port `source` because  it is bound to `p:empty`?

If I remember right, XMLCalabash and MorganaXProc found two different solutions to this problem.

What to do? We could use

1. base-url of the stylesheet
2. base-uri of p:xslt
3. base-url of p:declare-step
4. base-uri of pipeline.

Suggestions?

**Comment by ndw** [comment]
I think the XSLT answer is that it's the base URI of the stylesheet.

**Comment by xml-project** [comment]
Will add a note to the specs.

**Comment by xml-project** [comment]
Fixed with #191
