### ISSUE TITLE
Inconsistency in the validation document

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#196]
In the preamble it reads:

> the mandatory report document should be valid with respect to the [XVRL] schema.

But for p:validate-with-schematron it reads:

> In addition to the mandatory XVRL report, a Schematron Validation Report Language (SVRL) report should be provided on the report port.

This seems to be the reason why @gimsieke and me disagree in #195

**Comment by gimsieke** [comment]
I don’t see this contradiction. 

There is a mandatory report document that **should** be valid XVRL (I didn’t write **must** because I thought that processors shouldn’t be considered non-conformant if they sloppily generate not-fully-valid XVRL). But at least they should try their best in producing XVRL vocabulary in the primary, mandatory report document.

Then there may be additional report documents in other vocabularies. The Schematron validation should also emit an SVRL document on the `report` port in addition to the mandatory XVRL.

I’m pretty sure there is some misunderstanding among us but I don’t see yet how you interpret the text or what I fail to recognize as contradictory.

**Comment by xml-project** [comment]
Obviously we have to completely different readings of this: I read "should be valid with respect ..." as "might be XVRL, but also might be something different".

But if there is a "mandatory XVRL report" I would expect this step to produce valid "XVRL".

If you don't think its contradictory, feel free to close this issue or change the text, so stupid people like me are not bothered.

I came to the conclusion that this whole discussion is simply void as we talk about an optional step. If think user will not want it, I am free not to implement it. So: Go on.

**Comment by gimsieke** [comment]
I propose then to rephrase it:

> Unless another serialization format is requested, the mandatory report document **must** be an [XVRL] document.

So we don’t say anything about validity here.

I wouldn’t rule out the possibility of JSON or turtle text output for the primary report (at user’s request, and subject to availability of these other XVRL serializations). But if we want to do without these hypotheticals in this version of the spec, we can simply say:

> This primary report **must** be an [XVRL] document.

**Comment by mricaud** [comment]
Hi folks ! 
Maybe toi late but IMHO, it would ne great that any validation step has a mandatory ans valid XVRL output port. This allow users to merge multiple XVRL into a single one if they want the whole validation report at once.
Off course this doesn't prévention to have other kind of report like SVRL for schematron, but as a specific output port si people that don't care about XVRL van access other specific report.
Maybe I missed some considerations but that was my feeling :)

**Comment by gimsieke** [comment]
Hi @mricaud, I will take your comment and @xml-project’s comment to https://github.com/xproc/3.0-steps/pull/213#pullrequestreview-288109333 into account tomorrow. (I have a project deadline to meet tomorrow, therefore I’m a bit slow on this.)

**Comment by ndw** [comment]
At the XProc WG meeting in Cologne: we will add an "output-format" option with an implementation defined set of values (obviously, "svrl" and "xvrl" would be good choices).

**Comment by ndw** [comment]
We should raise a specific error if the requested format isn't possible.

**Comment by gimsieke** [comment]
When dealing with this issue, also wrap all XML validations into a section of its own so that the common features only apply to XML validation steps, not to future JSON or RDF validation steps.

**Comment by xml-project** [comment]
addressed in pr #213

**Comment by xml-project** [comment]
Adressed with #213
