### ISSUE TITLE
Add sort key option to p:text-sort

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-steps#197]
@xml-project pointed out that the `stable` option on `p:text-sort` does not makes sense as it is specified. Lines are either the same or not.

What we can do is add an option that defines a sort key as an XPath expression on the step. Proposal: `select`. This expression would act on every line (so you can do things like `substring(., 1, 3)` to sort on the first three characters). I think this is very useful and `stable` will again make sense.

**Comment by xml-project** [comment]
👍 
I we do this, I am not sure, @data-type is still necessary.
