### ISSUE TITLE
Missing case in p:archive?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#203]
Unless I overlooked something, there seems to be a missing case. The [specs](http://spec.xproc.org/master/head/steps/#cv.archive-zips) say on 'update':

> - Any entry in the manifest that does not exist in the ZIP file provided on the archive port is added.
> 
> - For any entry that does exist in the ZIP file provided on the archive port, a timestamp compare is done. When the entry in the manifest is newer than the entry in the ZIP file provided on the archive port, it is replaced. Documents that are either specified in the manifest or come from the source port have no timestamp and will always cause a replace to be done.
> 

Now image I run update on a zip containing entries, that are not mentioned in the (constructed) manifest? What do we say about them?

I suppose these entries should be copied to the archive appearing on port `result`, but should be moved to the end of the zip because the manifest imposes an order on the entries.

Right?

**Comment by eriksiegel** [comment]
Sounds ok to me. Bit of an edge case I suppose.

**Comment by xml-project** [comment]
@ndw Yes, order makes it complicated and results in a lot I/O. But the specs say:

> The p:archive step **should** strive to retain the order of the c:entry elements when constructing the archive. For instance, an e-book in EPUB format has a non-compressed entry that must be first in the archive. It should be possible to construct such an archive using p:archive.

(Hint: The should in the last sentence is not in terminology).

I pretty sure creating ePub is a requirement for some users.

**Comment by eriksiegel** [comment]
Decision: Manifest imposes order, everything else is implementation defined
Manifest entries come first

**Comment by eriksiegel** [comment]
Work moved to #251
