### ISSUE TITLE
Different error descriptions with same code

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#207]
In p:archive we say:

> It is a dynamic error (err:XC0081) if the content type of a document on the archive does not match the given archive format as specified in the format option.

On p:archive-manifest and p:unarchive is reads:

> It is a dynamic error (err:XC0081) if the format of the archive does not match the format as specified in the format option.

Not sure whether this is intentional. (From the perspective of an implementer they may be interpreted in two different ways.)

**Comment by eriksiegel** [comment]
I think I've written this and no, it is not intentional. Fix it?

**Comment by xml-project** [comment]
As zip archives can come with many different mime-types, I would suggest to use second wording.
