### ISSUE TITLE
Should/Does p:store with "file://" also create folders?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#217]
From a private conversion:

In `p:store` we just say that it is an error, if the resource can not be stored (which is obvious), but we do not say, what the step should undertake to make storing possible.

At least for "file:///" the question might come up, whether a processor will create all the folder necessary for storing the resource with the given URI.

I do not argue, a processor should do this, but I argue that we should **say** what a processor is expected to do or not to do.

**Comment by ndw** [comment]
I agree that the most important thing is to document the behavior.

Does the JVM create them for you by default? I think it might but I could be wrong.

**Comment by xml-project** [comment]
> Does the JVM create them for you by default? I think it might but I could be wrong.

Nope! I think there is a switch in the JAVA API, but it is off by default.

What behaviour would you prefer:

1. Creating folders
2. Raising an error?

**Comment by ndw** [comment]
I believe that Saxon creates folders by default, so if there's no compelling reason to be different...I'd do that.

**Comment by xml-project** [comment]
> I believe that Saxon creates folders by default ....

Do you mean Saxon's command line behaviour?

**Comment by xml-project** [comment]
@ndw You are right on XSLT: `xsl:result-document href="create/some/folder/doc.xml"` creates the required folders, so the document can be stored.
I think we should adapt this behaviour for `file://` on `p:store`. 
Will try to come up with a proposal.
