### ISSUE TITLE
Open question on parameter mapping in p:xslt for 1.0 stylesheets

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#222]
There is an editors box at the [end of p:xslt](http://spec.xproc.org/master/head/steps/#c.xslt.12) asking about the mapping of the parameters map to XSLT 1.0 stylesheets. 

In XProc 1.0 we mapped string to the parameters and I think we should continue to do so. Therefor I suggest, that an atomic value in the parameter map is converted to its string value (unless it is already a xs:string). This string is supplied to the stylesheet as value for the named parameter. If a key in the parameters map is associated with a node, a map, an array or a function, a dynamic error is raised.

Does that sound reasonable?

**Comment by eriksiegel** [comment]
@xml-project Does what you suggest above apply to XSLT **1.0** only? Or also to 3.0?

In case of 1.0: Yes, sounds reasonable

In case of > 1.0: Would be a pity if we had to cast everything into a string. But I'm not sure about what is technically possible to pass in to a stylesheet.

**Comment by xml-project** [comment]
@eriksiegel No, it is just for 1.0
I introduced three different section (calling 3.0, 2.0, and 1.0). 3.0. stylesheets get everything, 2.0 stylesheets everything but map, arrays, and function.

**Comment by Conal-Tuohy** [comment]
I would have thought that a node passed to an XSLT 1.0 stylesheet should produce the string value of the node rather than throw an error.

**Comment by xml-project** [comment]
@Conal-Tuohy Yes, may be. My point was to make sure, legacy 1.0 stylesheets still run. As you could not pass a node to a stylesheet via parameters in 1.0, I am not sure we need to introduce this as a new feature. Do you really think someone is going to write an XProc 3.0 pipeline calling an XSLT 1.0 stylesheet receiving the string value of a node via `parameters`?
I there is a use case, it would be fine with me, but I do not think it is.

**Comment by Conal-Tuohy** [comment]
Well I wouldn't of course be writing new stylesheets in XSLT 1.0, but I can certainly imagine being in the position of having a legacy stylesheet in XSLT 1.0, which required a parameter (necessarily a string), in which case I think I _would_ expect to be able to pass a node and have it interpreted as a string, as if by the XPath `string()` function. That would certainly be my expectation.
```xml
...
<p:http-request/>
<p;xslt parameters="map{'result-code', /c:response/@status)" ... />
```
Of course I could explicitly convert the `/c:response/@status` to a string with the `string()` function, but it makes sense to me if the automatic rules for type-casting values of XSLT 1.0 parameters are simply explicitly defined with reference to the `string()` function.

**Comment by xml-project** [comment]
Good point. It is not a big deal to change the prose and the implementation for this case. Will do.
Objections?

**Comment by gimsieke** [comment]
None

**Comment by eriksiegel** [comment]
Not at all, good point.
