### ISSUE TITLE
Operative definition of error in p:uncompress needed

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#229]
In [p:uncompress](http://spec.xproc.org/master/head/steps/#c.uncompress) we have two errors:

- It is a dynamic error (err:XC0200) if the compression format does not match the format as specified in the format option.

- It is a dynamic error (err:XC0202) if the compression format cannot be understood, determined and/or processed.

While implementing it is unclear, under which conditions a processor should raise XC0200.

**Comment by ndw** [comment]
Indeed. I suppose you could raise XC0200 if the format was ZIP and the file format was TAR. But the likelihood is that you'd attempt to unzip it and get an error, raising XC0202.

I'm fine with abandoning XC0200.

**Comment by eriksiegel** [comment]
Fine with me, I'll remove XC0200

**Comment by xml-project** [comment]
Thank Erik. I can resolve this issue too. I just was not sure whether you had a special error case in mind which I missed.

**Comment by eriksiegel** [comment]
@xml-project No I did not had a special case in mind, just didn't realize the implications. I don't know when I'll come around to doing this, so if this small thingy is in your way when implementing Morgana, please go ahead.
