### ISSUE TITLE
Incorporate EXProc steps

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-steps#24]
We have to decide what we're going to do with all the EXProc steps (http://exproc.org/). They've proofed very useful. Some things to decide upon:

- Incorporate these steps into the XProc standard step library (into the p: namespace). Can we do that without consulting with the EXProc people (don't want to be impolite...)?
- Keep them as is or make them more XProc 3.0 like? For instance the zip steps now all load a zip file from a URI, but in 3.0 this can become a port.

**Comment by xml-project** [comment]
add 1: I would like them to be in XProc's namespace. @ndw should know, who "the EXProc people" are, apart from himself.

add 2: I just had a quick look and I think, we could have all steps proposed under "Operating System utilities" and "File Utilities" as they are. There might some changes necessary, if I remember right from my implementation of these steps, but I think we should do this, as we go along.

For the steps proposed under "Other steps" I think you are right that we should adapt them to XProc 3.0. Especially the zip/unzip - compress/uncompress steps need some revisions to make actually useful in an XProc 3.0 environment. But I think there are some proposals for this.

**Comment by eriksiegel** [comment]
If we can agree that we want to add them *and* put them in the p: namespace:

What I would like to do is go over these exproc steps and add them to the our step library without much ado first. I could identify them, and the things I think need some more discussion, with a [TBD] marker or whatever (is there something for this?). 

Because: I think its important to have at least "stubs" for every step we are likely going to implement. It helps getting an idea of the workload we're still facing. It will also aid the discussion I think. And, assuming at least some of the descriptions will be uncontroversial, it is work done.

So the result will be that the step library will be extended with steps with some "still under discussion" label/text attached.

@xml-project  @ndw @gimsieke Would that be ok with you or do we need to discuss all new steps *before* we enter them into the spec?

**Comment by gimsieke** [comment]
We discussed in London two years ago which steps to standardize (and possibly to modify), including Calabash extensions, see https://github.com/xproc/Workshop-2017-06/wiki/Minutes#user-content-step-library 

Some EXProc steps would need to be renamed, `pxf:info` → `p:file-info`, `pos:info` → `p:os-info`, `pxf:delete` → `p:delete-file`

I agree that we should have at least placeholders for the EXProc steps.

**Comment by xml-project** [comment]
@eriksiegel +1

**Comment by eriksiegel** [comment]
First part of this in #21

**Comment by xml-project** [comment]
Can we close this?. Seems to be solved

**Comment by xml-project** [comment]
Solved with pr #626 and #630
