### ISSUE TITLE
Port "manifest" on p:archive with more than one document

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#244]
Sorry, I had this problem on my list but forgot to raise an issue for it: Port "manifest" is a sequence port, but as far as I understand the specs, it is only explain what happens if no document or one document appears.
What is the semantics of more than one manifest document? Are they joined together? Which one takes precedence?
Or is it simply an error to provide more than one document on this port?

**Comment by eriksiegel** [comment]
The port is of type sequence because it must be able to accept the empty sequence. More than one manifest is an error IMHO. 

We have no proper semantic in the language to express this... (and I don't think we should add them in this final stage)

**Comment by xml-project** [comment]
👍
