### ISSUE TITLE
p:unarchive needs a fix

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#251]
As a consequence to the changes for
https://github.com/xproc/3.0-specification/issues/889
we need to fix p:unarchive. The specs says:

> The base URI of an unarchived document appearing on the result port is the relative path of this document as it was in the archive. For instance, the base URI of an unarchived file called xyz.xml that resided in the specs subdirectory in the archive will become specs/xyz.xml.

But document's base URI have to be absolute now, so we have three options:
(1) resolving the relative URI against the baseURI of the archive or
(2) providing an additional option with the base uri used to resolve the relative uris.
(3) both: first (2), but I not option is provided, (1).

Any opinions?

**Comment by gimsieke** [comment]
I think “resolve against the archive’s base URI” feels natural, and it is flexible since you can change the base URI of the archive prior to unarchiving.
Example: `resolve-uri('spec/3.0-spec.xml', 'file:/tmp/3.0-spec.zip') ⇒ file:/tmp/spec/3.0-spec.xml`

**Comment by xml-project** [comment]
On 11-31 we decided that the answer is (3).

**Comment by eriksiegel** [comment]
There are several related issues that can be closed, because they're all going to be resolved by this one:"

* #256 
* #203
