### ISSUE TITLE
Legacy from 1.0: What are the output media types of p:xslt (and p:xquery)

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#26]
# What are the output media types of p:xslt (and p:xquery) 

>This is an aggregation of the discussion on "What are the output media types of p:xslt (and p:xquery)" ([Issue 117 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/117))

**Opened by: ndw on 2014-11-18, 23:19h**

## ndw said on 2014-11-18, 23:19h:

And how are they determined? 

	On 2015-10-07, 14:38h: ndw added this to the XProc 2.0 LC milestone.

**Comment by ndw** [comment]
Overtaken by events, see the discussion in the language spec.
