### ISSUE TITLE
Check p:directory-list

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#272]
On p:directory-list we currently [say](https://spec.xproc.org/master/head/file/#c.directory-list):

> The result document produced for the specified directory path has a c:directory document element whose base URI, attached as an xml:base attribute, is the absolute directory path (expressed as a URI that ends in a slash) and whose name attribute (without a trailing slash) is the last segment of the directory path.

To me it would make sense to say, that the base URI of the resulting document (not the base URI of the c:directory element) has the base URI property.

**Comment by gimsieke** [comment]
I agree. We can add: 

> The same base URI is attached as the resulting document’s `base-uri` property and, accordingly, as its document node’s base URI.

**Comment by xml-project** [comment]
Fixed with pr #275
