### ISSUE TITLE
Does p:set-properties remove the base URI of a document?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#281]
@ndw and me disagree about the result of a test in the test suite. The original discussing is [here](https://github.com/xproc/3.0-test-suite/issues/327), but the question is this:

Suppose I have a `p:set-properties` with `merge=false` and the map in `properties` does not have an entry for `base-uri`. What about the base URI of the document on port `result`?

1. It does not have a base URI because there is no entry `base-uri` in `properties`. 

2. It does have the same as the document on port `source` because there is not entry for `base-uri` and therefor the base URI of the document is not changed.

I am not in favor of any answer, but would argue, that if (2) is the right answer, we should explicitly say in the specs, that the resulting document does not have a base URI in this case.

**Votes in please!**

**Comment by gimsieke** [comment]
In the interest of allowing people to remove document properties, we should specify:

> If `merge` is `false` then only the properties supplied in the `properties` map will be attached to the document, that is, all other properties (with the exception of `content-type`) will be effectively removed.

**Comment by xml-project** [comment]
Removed my assignment, so @gimsieke could edit his text.
