### ISSUE TITLE
How is name constructed if relative-to is undefined?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#296]
On `p:archive`, suppose `relative-to` is not specified. If a document appears on the `source` port that is not in the manifest, how is a name constructed from the base URI?

Just take the path portion of the URI?

It's an error if the URI scheme is not hierarchical?

**Comment by gimsieke** [comment]
Yes, that’s what I thought, the path portion.

Does “absolute” imply “hierarchical”? Then we ought to be safe since base URIs need to be absolute and RFC compliant.

**Comment by ndw** [comment]
I think `urn:on:one:cares:about:this:scheme:anymore` is an absolute URI. But I'll double check.
