### ISSUE TITLE
Step "p:parameters" needs some clarifications or should be removed

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#30]
`p:parameters` is defined with the following signature:
````
<p:declare-step type="p:parameters">
     <p:output port="result" content-types="application/xml"/>
     <p:option name="parameters" as="map(xs:QName,item()*)?"/>     
</p:declare-step>
````
The description only says, that the value associated with a key in the map is represented as attribute `value`, but it does not say, what should happen, if:

1. The map-value is a sequence of more than one element,

1. The map-value is a node, and 

1. The map-value is an array, a map or a function.

All in all I am not sure we really need this step (except may be for legacy reasons), because `p:cast-content-type` can be used to convert maps into xml-documents using the specifications of `fn:json-to-xml()'.

**Comment by xml-project** [comment]
@gimsieke and me talked about this on Dec. 13th call and we came to the conclusion, that it is better to cover this conversion with p:cast-content-type. We might use option $parameters to mark that we want a c:param-set representation of the map and not the XPath-representation. See also the issue on p:make-map() in the specification repo.

**Comment by ndw** [comment]
In February 2019, we decided to remove this step.
