### ISSUE TITLE
Merge error code on archive steps

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#300]
@ndw and I had a longer discussion in the [test suite repo](https://github.com/xproc/3.0-test-suite/issues/343) about the precise situation to raise XC0081 or XC0085.

I therefor propose to change XC0085 to:
> It is a dynamic error (err:XC0085) if the format of the archive does not match the specified format, cannot be understood, determined and/or processed.

XC0081 should be removed.

**Comment by ndw** [comment]
Agreed. Remove `err:XC0081`, adjust `err:XC0085` as suggested.

**Comment by xml-project** [comment]
Will change tests too.
