### ISSUE TITLE
Clarify the concept of a line for text sort

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#301]
In a discussion in the [test suite repo](https://github.com/xproc/3.0-test-suite/issues/346) @ndw discovered that the concept of a line for p:text-sort needs clarification:

````
<p:text-sort>
  <p:with-input>
    <p:inline content-type="text/plain">C
D
B
A
</p:inline>
</p:with-input>
</p:text-sort>
````
The problem raises from the "new-line" after "A". If lines are **separated** by "line-line" this text has 5 lines (the last is empty) and the correct result is:
empty line, A B C D

If lines are **terminated** by "new-line" we have 4 lines and the correct result is "A B C D".
But then, what to do about:
````
<p:inline content-type="text/plain">C
D
B
A</p:inline>
````

**Comment by xatapult** [comment]
The usual thing that happens in theses cases (in editors and in programs that interpret text files)  is to consider the last line-ending *optional*. So if there's no LF after the last line (as in your second example) it is silently assumed to be there.

This means that both examples above yield the same result.

**Comment by xatapult** [comment]
Stated in a rule: Lines are *terminated* with a line-end (usually LF). For the last line this is optional.

**Comment by xml-project** [comment]
@xatapult 👍 This is (I think) what Norm and I would like to have. Let's state this in the specs.

**Comment by ndw** [comment]
I'm fine with making the final trailing newline optional on input. Do we want to say whether the output is required to, required not to, or may optionally have a trailing newline?

**Comment by xml-project** [comment]
Yes, we should do this because I would expect, that a p:text-count before and after a p:text-sort return the same value. Shouldn't it?

**Comment by ndw** [comment]
Trailing newline is optional, but all text steps must behave consistently. On output, the trailing newline should be output.
