### ISSUE TITLE
Add 'severity' to the c:error attributes

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-steps#31]
It is desirable to optionally flag the severity of an error in a [c:error element](http://spec.xproc.org/master/head/xproc30/#cv.error), either with an attribute named `severity` or `role`, the latter being in line with existing use in Schematron. There should be a suggested (or fixed?) list of values, namely 'info', 'warning', 'error', and 'fatal-error'.

**Comment by ndw** [comment]
We moved #397 from 3.0-specification to here (3.0-steps) as issue #15 

I'm moving this related issue as well.

**Comment by ndw** [comment]
Overtaken by events; this is now part of XVRL.
