### ISSUE TITLE
Granularity of XD- and XC-type errors

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#32]
Related to issue #341 a more general question comes up to me: Since we have now multiple p:catch to handle different types of errors, does it still make sense to have such molecular errors as XD0011:

> It is a dynamic error if the resource referenced by a p:document element does not exist, cannot be accessed, or has an XML content type and is not a well-formed XML document.

Authors might want to have different error mechanisms for non existing documents, not accessible (protected) document or not well-formed documents. The my understanding such a molecular type of error was ok in XProc 1.0 were the basic audience for error message was human. In XProc 3.0 pipelines will consume errors very much, so I think we need more specific codes to make this possible.

One could argue that the pipeline should inspect the error message (in contract to the error code), but this is the path to non interoperable pipelines because different processors will display different error texts and users might use the pipeline in different language environment and want their error message e.h. in spanish.

**Comment by eriksiegel** [comment]
This is a reminder

**Comment by ndw** [comment]
Achim and I discussed this and agreed that we could do better in terms of the granularity of some of the error codes, but in the interest of getting the 3.0 spec finished, we're going to close this issue for now. If pipeline authors identify cases where finer granularity would be useful, we can always add more error codes in the future.
