### ISSUE TITLE
Document property preservation in the absence of an input port

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-steps#325]
The following steps state that “no document properties are preserved” despite the fact that there is no input port:

- [`p:www-form-urldecode`](https://spec.xproc.org/master/head/steps/#c.www-form-urldecode)
- [`p:www-form-urlencode`](https://spec.xproc.org/master/head/steps/#c.www-form-urlencode)
- [`p:directory-list`](https://spec.xproc.org/master/head/file/#c.directory-list) (also: add remark that `base-uri` is the URI of the directory)
- [`p:file-copy`](https://spec.xproc.org/master/head/file/#c.file-copy)
- [`p:file-delete`](https://spec.xproc.org/master/head/file/#c.file-delete)
- [`p:file-info`](https://spec.xproc.org/master/head/file/#c.file-info)
- [`p:file-mkdir`](https://spec.xproc.org/master/head/file/#c.file-mkdir)
- [`p:file-move`](https://spec.xproc.org/master/head/file/#c.file-move)
- [`p:file-file-create-tempfile`](https://spec.xproc.org/master/head/file/#c.file-create-tempfile)
- [`p:file-touch`](https://spec.xproc.org/master/head/file/#c.file-touch) (it is not specified what is contained in the result document if the step succeeds; also “one of the following errors” precedes a list of exactly one possible error)
- [`p:os-info`](https://spec.xproc.org/master/head/os/#c.os-info)

I’d say that the concept of property preservation only applies to steps with a (primary) input port.

Apart from the parenthesized remarks in the list above that might require special wording, a proposal for a general change of the document property sentence for these steps is something like this:

> The resulting document only has the `content-type` property. It does not have a `base-uri` property.

or 

> The resulting document has no properties apart from `content-type`. In particular, it has no `base-uri`.

**Comment by ndw** [comment]
That seems reasonable. I considered it briefly the other day when I was going through the steps for something else, but apparently neglected to actually do it.

**Comment by gimsieke** [comment]
Does anyone have a preference for one of the wording alternatives given above?

**Comment by xml-project** [comment]
Nope!

**Comment by ndw** [comment]
I think the latter wording is a little better. But shouldn't the `p:directory-list` step use the directory as the base-uri? I guess it doesn't really matter since (as I recall!) it will have an `xml:base` attribute on the document element.

**Comment by gimsieke** [comment]
Yes, the `p:directory-list is supposed to have `@xml:base` on `/c:directory`. 

I think it is convenient to stipulate that, in addition, the document will have the same directory URI as its `base-uri` property, instead of having no `base-uri` property and therefore no base URI. 

Without it, `base-uri(/*)` will report the directory’s base URI while `base-uri(/)` will give an empty sequence.

**Comment by ndw** [comment]
Precisely!
