### ISSUE TITLE
Should p:file-touch create an empty file if href does not exist?

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-steps#343]
While I was addressing #325 I noticed that `p:file-touch` only sets the modification date/time of _existing_ files. 

Should it mimic Unix `touch`’s behavior in that it also creates an empty file if the file specified by `href` does not exist (and if it is permitted at the given location)?

**Comment by Conal-Tuohy** [comment]
i think so, yes.

**Comment by ndw** [comment]
Yes, absolutely.
