### ISSUE TITLE
Header "content-type" for multipart-request

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#347]
While implementing the new approach, the following problem came up:
The specs [says](https://spec.xproc.org/master/head/steps/#c.http-multipart-request):

> The overall content type of the request is taken from the “multipart-content-type” parameter; if that parameter is absent, the value “multipart/mixed” is used.

What to do, if a "content-type" is present in option "headers":
(1) Simply ignore,
(2) Raise error,
(3) Raise error only, if the two entries differ.

As we have all three approaches on other occassions in p:http-request, none seems more natural to me than the other.

But we need to say something - And I need to know, what to implement.

**Comment by ndw** [comment]
It's a good question. If I step back, it seems like we could make a high-level choice: either the implementation is supposed to interpret the values in the headers map and those values influence its behavior or the headers map is just copied to the request and exists for extra things that aren't part of the core HTTP spec.

I had the latter interpretation in mind, but we now have several places where that leads to potential conflicts. We should probably treat those conflicts in the same way. If the goal is to take the latter approach, I don't think option 3, comparing them and raising an error only if the values differ is the best approach. We should either ignore them or it should be an error if they exist at all in the headers map.

But part of my reason for thinking we would do the "just copy" approach is that it used to be much harder to specify headers than it was to specify options so it was at least a little bit about ease of use. Today, there's not much difference between:

```
  <p:http-request parameters='{"multipart-content-type": "multipart/mixed"}'/>
```

and

```
  <p:http-request headers='{"content-type": "multipart/mixed"}'/>
```

In fact, I think you could make an argument that the headers case is simpler (it's less typing) and easier (it uses HTTP-technology not our invented parameters).

If we took the former approach, going back to my original statement, and argued that header values influence step behavior, we could remove the `multipart-boundary`, '`multipart-content-type`, and `transfer-encoding` properties.

Would that be better?

**Comment by xml-project** [comment]
Ok, now I understand the reason why you made "multipart-content-type" etc. a parameter. To my understanding (before you made the last change) `parameters` control the configuration of the http client and the post-processing of the response. While `headers` are http headers which are all send with the request and partly influence the inner logic of the p:http-request step when constructing the request.

Therefor for me it would seem more natural to remove `multipart-boundary`  etc. from `parameters` and use the normal HTTP headers. I would argue that it could be more natural for authors to put all HTTP headers into headers (and let us sort it out), than to look up which is a header and which is a parameter.

Do that make sense?

**Comment by ndw** [comment]
Yes. Let me see if I can write up a quick pull request.
