### ISSUE TITLE
file steps: hrefs should be RFCs valid uris

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#351]
Do we agree that each href has to be a valid URI according to RFC?
Currently we require them to be valid instances of xs:anyURI but for reasons for consistence with the other steps, I think they should be valid URIs.
Thumbs up?

**Comment by gimsieke** [comment]
yes, we shouldn’t treat them differently in the file steps than we do in other standard steps

**Comment by xml-project** [comment]
Fixed with #384
