### ISSUE TITLE
File step: Error if operation is not supported for given scheme

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#352]
Currently only p:directory-list has an error to be raised if the operation is not supported for the given sheme. I would argue to have an respective error for each of the other file-steps. And I would argue, that we do not restrict the scheme to „file:“ so a processor could use file-steps to do the respective for other schemes, e..g. webdav operations with „http:“ or „ftp:“
Thumbs up?

**Comment by gimsieke** [comment]
👍

**Comment by xml-project** [comment]
Fixed with #384
