### ISSUE TITLE
Question on p:file-move

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#361]
The [specs](https://spec.xproc.org/master/head/file/#c.file-move) says:

> If the href option specifies a device or other special kind of object, the results are implementation-defined.

Could somebody please explain to me what this is supposed to mean.

**Comment by xatapult** [comment]
Well, what is says...

On Unix a file path can reference a pseudo file for some device.

**Comment by xml-project** [comment]
Hhmm, still not sure, I understand that. I know how to address a device (e.g. a printer) with "ipp:" or "smb:". Can you give me a hint what kind of device can be addressed by "file://".

**Comment by gimsieke** [comment]
`/dev/lp0` is a typical printer file system path, or `/dev/tty0` is a terminal device. They can be addressed by `href="file:///dev/lp0"` and `href="file:///dev/tty0"`, respectively.

**Comment by xml-project** [comment]
Thanks. Now I got the point.
