### ISSUE TITLE
Expected result of p:cast-content-type for param-set

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#366]
Currently the expected map type of `<p:cast-content-type content-type="application/json" />` for c:param-set is not precicely defined. See https://github.com/xproc/3.0-test-suite/pull/399

We should explicitly say that `map(xs:QName, xs:string)` is produced.

**Comment by xatapult** [comment]
❓  Why? A `c:param-set` is yaxd (yet another xml document). That's it a param-set doesn't make it special and IMHO shouldn't be treated special. Or am I missing something?

**Comment by xml-project** [comment]
@xatapult please see: https://github.com/xproc/3.0-test-suite/pull/399
@ndw and me had different expectations about what is supposed to be the result. So will users, won't they?

**Comment by ndw** [comment]
The only reason to support `c:param-set` as a special case in `p:cast-content-type` is to capture the XProc 1.0 semantics (for backwards compatiblity). If you look [in the 1.0 spec](https://www.w3.org/TR/xproc/#cv.param), you'll see that the semantics are that each `c:param` element produces a QName by composing the name with a namespace.
