### ISSUE TITLE
Add @content-type to the output of p:archive-manifest?

### ISSUE THREAD

**Issue by xatapult** [xproc/3.0-steps#368]
Still struggling with the best way to process zip file contents.

I think it would be useful to extend the output of `p:unarchive-manifest` and add a `c:entry/@content-type` attribute, containing the processor's guess of the entry's content type. So you can base further decisions on this, e.g. whether to unarchive this entry or not. Then you can keep big binary files untouched when you do something with a zip.

Currently you only get the entry's name and you have to implement your own guessing algorithm (based on the filename) whether to load it or not. Since such an algorithm is already present in the processor, that's double work.

Another (maybe even better and more generic?) way to do this would be to add a new custom function that provides you with the processor's guess of the content-type based on a resource URI.

There's one thing that might make this impossible or too costly: How a processor determines the content-type is implementation defined. This might mean that some processors will want to look at the contents of the file instead of at the URI.

**Comment by xatapult** [comment]
Given that `p:directory-list` also doesn't provide you with content type information, a `p:uri-content-type()` function (or whatever name) seems like a generic solution to this to me.

**Comment by gimsieke** [comment]
Both `p:directory-list[@detailed='true']` and `p:file-info` already return the content type if available. So I think it’s useful to have the same details in the manifest document that `p:archive-manifest` returns.

Beyond that, maybe a more general extension function `p:file-info()` might be useful. It returns the same information as the `p:file-info` step, only as a map.

**Comment by xatapult** [comment]
`p:directory-list` returns the content-type *optionally*. Achim's current implementation doesn't.

**Comment by xml-project** [comment]
Not speaking about the general case I would like to point out, that MorganaXProc-IIIse returns the content-type as described in the current version of the specs.

**Comment by xatapult** [comment]
@xml-project You're right, excuses. I overlooked it.

**Comment by xatapult** [comment]
> Beyond that, maybe a more general extension function p:file-info() might be useful. It returns the same information as the p:file-info step, only as a map.

That wouldn't solve the case of trying to get info on a file in an archive.

**Comment by xatapult** [comment]
We will add a @content-type to c:entry archive manifest
