### ISSUE TITLE
p:http-request is underspecified with respect to document properties as headers

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#369]
The spec says:

> If a single document appears on the source port, then document properties on that document may be added as additional headers. All of the document properties will be used as headers except “base-uri”, “serialization” and any property...

I think we should say that only document properties in no-namespace are added. Otherwise, what do you do with a document property named `ex:foo`. You can't use "ex:foo" as a name. Even if `{` and `}` are allowed in header names (which I doubt), you can't use the `Q{}` syntax because the URI is almost always going to contain a colon.

We could say that you use the local name, but then you will always have errors if there are different properties with the same local name.

**Comment by ndw** [comment]
I wonder, actually, if we should say that only headers in a particular namespace *should* be copied over. Today we have the situation that implementations are free to add additional properties. So it's difficult for users to predict what properties will exist.

(I just discovered this because I provide additional http properties as document properties, but that means if you copy them blindly across, you can wind up with weird http issues.)

**Comment by ndw** [comment]
Or maybe I should put those extra properties in a namespace?

**Comment by Conal-Tuohy** [comment]
I agree that not all document properties should be turned into headers. An XML namespace for HTTP headers seems on the face of it a good idea to me

**Comment by ndw** [comment]
General agreement at the editor's call on 18 March that we'll say that documents in [namespace to be determined] will be copied as headers.
