### ISSUE TITLE
Archive names in zip can have a leading /

### ISSUE THREAD

**Issue by xatapult** [xproc/3.0-steps#385]

**Comment by xatapult** [comment]
Would this be a correct way of putting it?

>The regular expression is matched against the path of the entry in the archive. Depending on how the archive was constructed, this path can be with or without a leading slash. Usually it will be without. For archives constructed by `p:archive` no leading slash will be present.

**Comment by xml-project** [comment]
Sounds good to me as far as I understood @ndw's point.
