### ISSUE TITLE
Error codes for p:validation steps are missing

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#397]
The only error code defined in the specs is:

> It is a dynamic error (err:XC0054) if the assert-valid option is true and any Schematron assertions fail or reports succeed.

I think there should dynamic errors defined for other error situations, e.g. what error to raise, if the document on port "schema" is not valid schematron.

**Comment by ndw** [comment]
Fine by me. Do we have errors for what happens if the schema document provided for other validation steps is invalid?

**Comment by xml-project** [comment]
Not as far as I can see.

**Comment by xatapult** [comment]
We have to add an error code for invalid schema documents.

**Comment by xml-project** [comment]
Consensus: Let's have more errors.
