### ISSUE TITLE
p:http-request: How is parameter 'fail-on-timeout' related to option "assert"

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#398]
Suppose a http request has a time out. What is supposed to happen:
fail-on-timeout | assert | expected error |
------------ | ------------- | -------------
true | 408 not caught | err:XC0078 |
false | 408 not caught | no error |
false | 408 caught | err:XC0126 |
true | 408 caught | ? |

So in the last case the expected behaviour is not clear (at least to me).

**Comment by ndw** [comment]
No, I don't think it's clear at all. You can't raise two exceptions so we just have to pick one. I propose `err:XC0078` because it's more explicitly about timeouts.

**Comment by xatapult** [comment]
Postponed to next call

**Comment by xml-project** [comment]
See pr #402

**Comment by xml-project** [comment]
fixed with pr #420
