### ISSUE TITLE
Archive manifest processing

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#401]
The [specs](https://spec.xproc.org/master/head/steps/#cv.archive-manifest) says (behind the second yellow box):

> It is a dynamic error (err:XD0011) if the resource referenced by the href option does not exist, cannot be accessed or is not a file. These documents are stored in the archive “as is”; they must not be parsed and re-serialized.

I think taken together these two sentences might be missleading, saying

1. that an error is raised  and
2. the missing document is ignored and the original doc (in the zip) is preserved.

Suggestion: Flip the two sentences around because "These" in the second sentence is related to found documents, not to missing ones.

Did I miss something?

**Comment by xatapult** [comment]
Agree. I would say: just do it.

**Comment by xml-project** [comment]
@xatapult But not now. Have to prepare for a meeting, you know ;-))

**Comment by xml-project** [comment]
Hhm, I think the problem is bigger than I thought. As I noted about, in the section on [archive manifest](https://spec.xproc.org/master/head/steps/#cv.archive-manifest) we say that it is an error if the resource does not exists.
But then in the next section (Handling of ZIP archives) we says, not a non existing resource is ignored for update, create (because create is like update), freshen (because freshen is like update). And for delete it does not matter.
Could you please have a look at the specs and tell me that I am interpreting it right.
Is this really the behaviour we intend? A least for "create" I would expect it to be an error if the resource is missing, but may be I am wrong or have the wrong use cases in mind.

**Comment by xatapult** [comment]
Hmm. IMHO:

* For creating it makes sense to throw an error if  the manifest has a resource in it that can't be found
* For all other operations it makes sense to *not* throw an error if this happens 

Or we could decide not to throw errors on missing references in the manifest *always*. But then being sure your archive is correct (after creating, the most common case) is hardly verifiable. Hmmm.

I think this needs to be discussed in a call.

**Comment by xml-project** [comment]
Yap, some intuitions here.

**Comment by xml-project** [comment]
Addressed in pr #406

**Comment by xml-project** [comment]
Fixed with pr #406
