### ISSUE TITLE
Suggestions on p:os-exec

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#415]
@xatapult commented on pr #407:

> One small enhancement maybe: Define a default value of <p:empty> for the source port?

@ndw:

> One minor detail: If result-content-type is singular, I think error-content-type should be singular as well.

**Comment by xatapult** [comment]
Decisions:

> One small enhancement maybe: Define a default value of <p:empty> for the source port?

No. It would make it special. If you need this, wrap the step.

**Comment by xml-project** [comment]
We go for singular "error" on port and option
