### ISSUE TITLE
Small errors in xproc.rng: some attributes are actually mandatory

### ISSUE THREAD

**Issue by GerbenAbbink** [xproc/3.0-steps#440]
We are using xproc10.rng and xproc30.rng for code completion and we have found an error: All attributes that are "required" in the XProc standard are optional in the relax schema. For instance:

Here "attribute-name" is "required":
https://spec.xproc.org/master/head/steps/#c.add-attribute
    <p:option name="attribute-name" required="true" as="xs:QName"/>

Here "attribute-name" is "optional":
https://spec.xproc.org/master/head/xproc/xproc30.rng
    <element name="add-attribute">
      <optional>
        <attribute name="attribute-name">
          <data type="QName"/>
        </attribute>
      </optional>

We have found so far:
	add-attribute		@attribute-name
	add-attribute		@attribute-value
	add-attribute		@match
	delete			@match
	directory-list		@path
	error			@code
	filter			        @select
	wrap			@match
	wrap			@wrapper
	xsl-formatter		@href

**Comment by ndw** [comment]
Unfortunately, it's not possible to make the option shortcut forms mandatory because, this has to be allowed:
```xml
<p:add-attribute>
  <p:with-option name="attribute-name" select="/doc/name">
    <p:pipe ...>
  ...
</p:add-attribute>
```
