### ISSUE TITLE
Error code are overtaken by history on p:run

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#448]
As it seems, the error codes in the p:run document where not registed in the error page in the wiki. The codes in the document are now used by other steps.

**Comment by ndw** [comment]
Oops. Just update them, I guess.

**Comment by gimsieke** [comment]
I see errors C0080, C0081, and C0082 in the p:run document. All of them have been registered by Norm [in June, 2018](https://github.com/xproc/3.0-specification/wiki/Error-Codes/7c91ce4bcba0bf82c10f975bbcfcdffd446ed6ff).

**Comment by xml-project** [comment]
Yes, but C0080 and C0081 are now used in connection with p:archive.
See:
https://spec.xproc.org/lastcall-2020-08/head/steps/#err.C0080

So I think it is necessary to have new error codes there.
