### ISSUE TITLE
version attribute on p:declare-step / p:library in p:run

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#449]
Contrary to the example given for p:run, I think that a version atrribute on p:declare-step / p:library is required for a pipeline to be executed by p:run. The specs say:

> If the p:declare-step has no ancestors in the XProc namespace, then it must have a version attribute. 

In the example the pipeline has an ancestor in XProc's namespace, but once the document arrives on the input port of p:run it is impossible for the step to know whether this was the case.

**Comment by ndw** [comment]
I agree.

**Comment by xatapult** [comment]
Me too

**Comment by gimsieke** [comment]
In https://github.com/xproc/3.0-steps/issues/447#issuecomment-674533271, I added the version attribute to the dynamically executed pipeline.

**Comment by xatapult** [comment]
The step p:run runs must have a version attribute

**Comment by gimsieke** [comment]
Was already addressed with f24f398 / PR #461

**Comment by gimsieke** [comment]
Changed 3.1 to 3.0 in the example (PR #472, commit 34043bc)

**Comment by ndw** [comment]
I think this is resolved.
