### ISSUE TITLE
please clarify relative-to option for p:archive

### ISSUE THREAD

**Issue by mkraetke** [xproc/3.0-steps#462]
In the spec it is stated that "The relative-to option is used in creating a manifest when no manifest is provided on the manifest port." For the reader remains unclear what an XProc implementation should do when both a manifest and an URI via `relative-to` is provided. IMHO, a dynamic error should be raised. Additionally, there is the text "If the option is relative". I think this must be "If the URI is relative".

**Comment by xatapult** [comment]
@mkraetke Hi Martin, thanks for the comment. We will take it up in our XProc editors meeting this week.

**Comment by xatapult** [comment]
Manifest has precedence

**Comment by gimsieke** [comment]
Editors’ call today: Manifest has precedence
