### ISSUE TITLE
p:run: Suggestion for prose change

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#465]
Currently the specs reads:

> The default readable port of the p:run step becomes the default readable port of the pipeline.

It took me about 5 times of reading and a phone call to understand what that sentence means.

Here is a suggestion to make it more understandable (to me):

> The default readable port of the p:run step supplies the context item needed to evaluate the XPath expression provided by the `select` attribute in p:run-option. Additionally the default readable input port is connected to the p:run-input explicitly or implicitly marked as `primary`, if no explicit connection is provided.

I do not claim this to be perfect, but I think it does hint the direction.

**Comment by ndw** [comment]
I think it's an improvement. Grammatically, I might go for this:

> The context item used to evaluate expressions on p:run-option comes from the default readable port of the p:run step. Additionally, if p:run-input implicitly or explicitly identifies a primary input port, the default readable port will be connected to it if no explicit connection is provided.

I think that says the same thing.

**Comment by xml-project** [comment]
Thanks, Norm. This is of course way better.

**Comment by gimsieke** [comment]
Consensus: Go with Norm’s wording

**Comment by ndw** [comment]
Also, "yup".
