### ISSUE TITLE
If no explicit connection is given for p:run’s anonymous input, will the pipeline be read from the DRP?

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-steps#466]
Achim and I discussed this. At first we thought that it won’t make sense under any circumstance that someone might want to use the DRP for supplying the pipeline, because the DRP is already used for the pipeline’s primary input. 

On the other hand, it would be inconsistent if `p:run` were the only XProc step whose primary (only) input port isn’t connected to the DRP. 

There are scenarios (pipelines without a primary input, only with options maybe) where it can make perfect sense to supply the pipeline via DRP, without the need to connect it explicitly. 

So I’m in favor of letting both the pipeline and `p:run`’s anonymous input consume what’s on the DRP, in the absence of explicit connections. Maybe add a note that this is the specified behavior.

**Comment by gimsieke** [comment]
Consensus 2020-08-26: The anonymous port is non-primary, non-sequence

**Comment by xatapult** [comment]
@gimsieke Can this one be closed? It seems to be addressed.

**Comment by ndw** [comment]
Yes, I think so.
