### ISSUE TITLE
make p:run 3.0 again

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-steps#468]
As decided during editors’ call today

**Comment by gimsieke** [comment]
Sentence "Whether a processor accepts a pipeline as valid whose version number is not equal to 3.0 or 3.1 is implementation-defined." can be omitted now

**Comment by xatapult** [comment]
@gimsieke Can this one be closed? It seems to be addressed.

**Comment by ndw** [comment]
Seems like it to me.
