### ISSUE TITLE
In p:file-copy, does err:XC0157 apply during a recursive copy?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#478]
Suppose `/tmp/x/copytest/a` is a directory, but `/tmp/x/result/copytest/a` is a file. This request:
```
<p:file-copy href="/tmp/x/copytest/a" target="/tmp/x/result/copytest/a"/>
```
raises `err:XC0157` (I believe). But does this request?
```
<p:file-copy href="/tmp/x/copytest" target="/tmp/x/result"/>
```
I assume not. I assume that once you've started a recursive copy and you're doing overwrites, you just overwrite it.

**Comment by xml-project** [comment]
I do not know, whether this is helpful, but the behaviour you described is exactly what I do.
