### ISSUE TITLE
Given that p:file-copy has an 'overwrite' option, shouldn't p:file-move?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#481]
By my reading, `p:file-move` is silent about what happens in the overwrite case.

**Comment by xatapult** [comment]
? It says:

>It is a dynamic error (err:XC0115) if the resource referenced by the target option is an existing file or other file system object.

So a move attempt to an existing file/object is an error by my reading.

**Comment by ndw** [comment]
I just looked right past that. Thanks, Erik.

**Comment by ndw** [comment]
In my defense, `err:XC0158` and `err:XC0115` overlap. I'm not proposing to do anything about it, but having seen the special case of 0158, I failed to notice that it would be an error (0115) in any event.
