### ISSUE TITLE
What are the semantics for failure on a recursive p:file-copy?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#482]
I assume:
1. If `fail-on-error` is true, an exception is thrown on the first error and no further processing occurs. *No* attempt is made to "undo" any copying that might already have been performed.
2. If `fail-on-error` is false, processing continues past the first (and subsequent errors, if they occur), but eventually a `c:error` result is produced.

**Comment by ndw** [comment]
More consistent behavior proposed in private email is that the step stops at the first error, even when `fail-on-error` is false. I guess that makes more sense, but we should make the spec explicit.

**Comment by xatapult** [comment]
There is something to say for both. For me: just make a choice. And yes, it should be made explicit
