### ISSUE TITLE
Use of `as="xs:token"` is an error

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#490]
We have a number of steps that declare an option with enumerated values like so:

```xml
<p:option name="name" as="xs:token" values="('a','b','c')" select="'a'"/>
```

I believe this is an error. The default value `'a'` is a `xs:string`, `xs:string` is not a subtype of `xs:token`, and so the default value is statically an invalid type. That's bad. We could fix this with `value="xs:token('a')"`, but then you'd have to use `xs:token()` whenever you wanted to specify the value, so users would hate us. 😄 

Given that we're going to check the supplied value agains the list of values, there's no benefit in type checking against `xs:token`, or even `xs:string`, we should just remove the `as` type.

**Comment by gimsieke** [comment]
Ok
