### ISSUE TITLE
p:send-mail

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-steps#5]
I suggest that we introduce an optional step `p:send-mail` that is modeled after [`cx:send-mail`](http://xmlcalabash.com/docs/reference/cx-send-mail.html).

At the [London Workshop](https://github.com/xproc/Workshop-2017-06/wiki/Minutes), Achim also proposed to specify IMAP access, and we agreed to postpone inbound and outbound email handling altogether. 

We have recently encountered more use cases for sending mail than for reading mail, so we’d be interested in having `p:send-mail` in the standard library, regardless whether we also specify accessing incoming email in this iteration.

**Comment by xml-project** [comment]
I agree we need p:send-mail and I agree that cx:mail-send could be a blue print. Will come up with a proposal next week.

**Comment by xml-project** [comment]
Still working on this. Waiting to see, what p:http-request will come up with.

**Comment by xatapult** [comment]
On our last call we decided to make a separate optional spec for p:send-mail. 

@ndw I think you're the only one that knows how to add a separate spec and add to the publication toolchain?

**Comment by ndw** [comment]
Already completed
