### ISSUE TITLE
text/csv -> application/json

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#51]
I think we should have a step (or a method on `p:cast-content-type`) that converts a CSV document (text/csv) to an array of arrays.

Role model could be this XQuery library: https://github.com/grantmacken/csv

**Comment by eriksiegel** [comment]
No objection. Would there be any demand for such a step?

**Comment by xml-project** [comment]
Sometimes I have to deal with CSV (Excel output). In MorganaXProc there is an [extension](https://www.xml-project.com/documentation/morganaxproc-api-guide/advanced-api-usage/#wrappers) to convert it to xml on the fly. Being able to convert it directly to JSON (without the detour via xml) might be useful as well.

**Comment by ndw** [comment]
Consensus: we'll leave this unspecified in 3.0 and see what implementations do/what users request.

Implementors could invent a new step, or could extend p:load, or could do something else.
