### ISSUE TITLE
Clarify which dynamic error is reported for fatal error of a XSLT processor

### ISSUE THREAD

**Issue by dmj** [xproc/3.0-steps#52]
2.45 p:xslt reads:

> A dynamic error occurs if the XSLT processor signals a fatal error. This includes the case where the transformation terminates due to a xsl:message instruction with a terminate attribute value of “yes”. How XSLT message termination errors are reported to the XProc processor is implementation-dependent.

But does not specify which dynamic error is to be reported.

**Comment by ndw** [comment]
Per the 20 March editorial call, we should define that the error reported to XProc is the error raised by XSLT (err:XTTM9000 in the case of an `xsl:message` that doesn't specify an error code.
