### ISSUE TITLE
Error in grammar for p:os-exec

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#522]
The specs says the option is called "error-content-type" but the grammar says it is named "error**s**-content-type".
I would fix it, if I would know how.

**Comment by ndw** [comment]
What grammar, where? It looks correct [in the spec](https://spec.xproc.org/master/head/os/#c.os-exec) and in the spec's [steps.xpl](https://spec.xproc.org/master/head/os/steps.xpl)

In theory, the grammar is built from the step declarations in the spec, so they shouldn't get out-of-sync. "Shouldn't."

**Comment by xml-project** [comment]
In my **local** repo "3.0-grammar" steps/step-os/steps.rng
Sorry: Its already fixed in the repo. Working with an old local copy.
