### ISSUE TITLE
Attributes from p:os-info

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#523]
1. To my reading from the current specs on [p:os-info](https://spec.xproc.org/master/head/os/#c.os-info) it is not clear whether all names attribute should be present but have an empty value (mandatory for `cwd`) or if an implementation is free to leave out an attribute that does not apply.

Suggestion: All listed attributes *must* be present but can have an empty value.

2. I think it should be mandatory that all additional attributes are namespaced as with the result of `p:directory-list`.

**Comment by ndw** [comment]
I wonder why we established that precedent. It seems odd to me now that on a system where there isn't the concept of a working directory that the value should be "empty". I'm not sure "empty" is even well defined for an attribute. I assume that means an empty string. But I don't think any of those are going to be unavailable on any system that's likely to have an XProc implementation, so I don't think it's worth stressing about.

**Comment by xml-project** [comment]
Fixed with #524
