### ISSUE TITLE
Error if namespace axis is matched in p:delete

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#53]
In [p:delete](http://spec.xproc.org/master/head/steps/#c.delete) we currently say:

> It is a dynamic error (err:XC0062) if the match option matches a namespace node. Also, note that deleting an attribute named xml:base does not change the base URI of the element on which it occurred.

Since we use XPath 3.1 and there is no support for the namespace axis anymore, I think this error is obsolete now.

Did I miss something?

**Comment by eriksiegel** [comment]
I think you're right

**Comment by xml-project** [comment]
Thanks norm. I will check the XPath 3.1 specs and the Saxon documentation for this.

**Comment by xml-project** [comment]
Found this passage too. So we have to keep the error.
