### ISSUE TITLE
Move p:directory list?

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-steps#54]
Shouldn't p:directory-list be moved to the file steps?
The reason the file steps are optional (not everything has a file system) also applies to p:directory-list.

**Comment by xml-project** [comment]
+1

**Comment by ndw** [comment]
Achim, you've got another issue to edit one of the directory-list steps. If I move them while you're editing them, we'll just get a nasty merge conflict. Can you move them when you're making your other changes?

**Comment by xml-project** [comment]
OK, I see the problem. 

Have we finally decided to move p:directory-list (and p:load-directory-list)? Missed that.

> Can you move them when you're making your other changes? 

What changes do I have to make on p:directory-list? Though I am done.

**Comment by ndw** [comment]
I thought we had consensus on that, but if you disagree...

Anyway #59 is still open and assigned to you, so I assumed you were working on something.

**Comment by xml-project** [comment]
Nope, I agree - just lost the consensus.

> Anyway #59 is still open and assigned to you, so I assumed you were working on something.

OK, I thought you referred to required changes on p:directory-list which I left out.

Will move both steps to the file-steps.

**Comment by eriksiegel** [comment]
Done with #212
