### ISSUE TITLE
Signature of output ports of p:os-exec

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#540]
Output ports "result" and "error" are not declared as sequence. But there are surely cases, were result or error is empty.
What to return in this case for the different values of "result-content-type". An empty std:out will not be a valid XML document, nor a valid JSON document, nor a valid Text document.
My expectation:  The port is empty, but then it has to be declared as sequence.
What did I miss?

**Comment by xatapult** [comment]
I agree, sounds to me like a no-brainer oversight in the p:os-exec spec.
