### ISSUE TITLE
Question on options with p:run

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#542]
The [spec](https://spec.xproc.org/master/head/run/) says:

> Options of the dynamically executed pipeline that are not declared with p:run-option on the p:run invocation will receive an empty sequence as their value.

On a strict reading this suggests to me, that the option receives an empty sequence as their value even if a default value for this option is declared in the called pipeline.

Is this right? If not, what do I miss?

**Comment by xatapult** [comment]
Hmm. Strictly interpreting this text, I think you're right.

But it sounds completely counter-intuitive to me. So maybe it should read (we'll have to change that):

>Options of the dynamically executed pipeline that are not declared with p:run-option on the p:run invocation and that *have no default value* will receive an empty sequence as their value.

**Comment by ndw** [comment]
I agree, but why did we mentioned it at all? Given a pipeline with an option `myopt` run by `p:run`, if you didn't specify a `p:run-option` for that parameter, I'd expect nothing to be passed to the invoked pipeline and for normal defaulting rules to apply.

That would amount to the default value if it had one, the empty sequence if it didn't have one, and possibly a runtime error if the option was required to have a value.

**Comment by gimsieke** [comment]
We added this because of #534 and [this fix for it](https://github.com/xproc/3.0-steps/commit/e0137b146d6abc2eda28c072ba25c0cb3e9904da). And I agree with Norm’s proposed amendment.

**Comment by ndw** [comment]
Fixed by PRs.

**Comment by ndw** [comment]
We agree that an option that isn't provided should be treated just as if the option hadn't been provided on an ordinary running of the step.
