### ISSUE TITLE
The result port on p:compare is not primary?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#549]
That surprises me. Was that intentional, or an oversight?

**Comment by gimsieke** [comment]
Maybe this was intentional. In 1.0, the (single) output port `result` was explicitly designated as [`primary="false"`](https://www.w3.org/TR/xproc/#c.compare). But I’m not sure what the 1.0 reasoning for this was.

**Comment by xml-project** [comment]
Oh, suprise here too. And my implementation has "result" as primary.
May be it is just a copy-paste from 1.0, but given the other steps it would feel more natural to me, to have "result" as primary.

**Comment by xatapult** [comment]
I definitely think it should be primary.

**Comment by ndw** [comment]
I can't recall what he rationale was in 1.0. Possibly that it was "destructive" in the sense that it doesn't return the source document modified, it returns `c:result` marked true or false. But we fixed most of those in 3.0. I think it's very likely that Achim is correct and it's just an oversight.
