### ISSUE TITLE
How are err:XC0081 and err:XC0085 different?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#561]
`err:XC0081` is:

> It is a [dynamic error](https://spec.xproc.org/master/head/steps/#dt-dynamic-error) ([err:XC0081](https://spec.xproc.org/master/head/steps/#err.C0081)) if the format of the archive does not match the format as specified in the format option.

and a couple of paragraphs later, `err:XC0085` is:

> It is a [dynamic error](https://spec.xproc.org/master/head/steps/#dt-dynamic-error) ([err:XC0085](https://spec.xproc.org/master/head/steps/#err.C0085)) if the format of the archive does not match the specified format, cannot be understood, determined and/or processed.

Was the intent that 81 is "you said ZIP but this isn't a ZIP" and 85 is "I can't figure out what this is or you said it was a ZZ archive and I don't now what a ZZ archive is"?

**Comment by gimsieke** [comment]
Can we safely exclude the C0081 case (`format` option doesn’t match) from C0085? So that the latter then reads:

> It is a [dynamic error](https://spec.xproc.org/master/head/steps/#dt-dynamic-error) ([err:XC0085](https://spec.xproc.org/master/head/steps/#err.C0085)) if the format of the archive cannot be understood, determined and/or processed.
