### ISSUE TITLE
Error codes on p:archive and p:archive-manifest

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#564]
If I understand the consensus for issue #561 right, then p:archive is expected to raise XC0081 if the document appearing on port "archive" is not in the format (implicitly) defined by option `format`. XC0085 is reserved to other error conditions with the archive.

The same case can appear on p:archive-manifest, but there the error code XC0085 is expected. I propose to add XC0081 also to p:archive manifest with the same error text as for p:archive. As a consequence the error test for XC0085 for p:manifest should be changed as proposed by @gimsieke for p:archive.

Does this make sense? Or did I miss some aspects where the difference makes sense.

Hint: Test "ab-archive-manifest-006.xml " is related.

**Comment by ndw** [comment]
Yes, I think that makes sense.

**Comment by ndw** [comment]
Fixed by #565, I believe
