### ISSUE TITLE
Additional error condition for paged media steps?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#585]
Currently we have error conditions to be raised for p:xslt and p:xquery, if the dynamic execution fails. But we do not have error conditions to be raised, if p:xsl-formatter or p:css-formatter are not able to produce the requested documents. This might be the consequence of missing fonts etc. My processor therefor raises the generic error XD0030.
While writing a complex pipeline it's very difficult to generate meaningful error messages because of this limitation. The pipeline gets more complex as it needs to be because of this limitation.
I therefor propose to add an error condition for p:xsl-formatter and p:css-formatter raised, if the step is not capable of producing the requested paged media document.
Does this make sense?

**Comment by ndw** [comment]
Absolutely.

**Comment by gimsieke** [comment]
I was just about to type “Absolutely”…
