### ISSUE TITLE
Add a parameters map to p:uuid?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#587]
It strikes me as slightly weird that the `p:uuid` step says:

>Implementations must support version 4 UUIDs. Support for other versions of UUID, and the mechanism by which the necessary inputs are made available for computing other versions, is [implementation-defined](https://spec.xproc.org/master/head/steps/#dt-implementation-defined).

Wouldn't it make sense to add a `parameters` map option so that there's a **place** to provide the necessary inputs? Implementors could use extension attributes or something, I suppose, but it seems like there's plenty of precedent for having a `parameters` map for this purpose...

**Comment by xml-project** [comment]
I thought that "the mechanism" refers to some type of configuration, or an extension attribute. 
But yes, a parameters map is certainly a good way to do this.
