### ISSUE TITLE
p:ixml or p:invisible-xml?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#625]
The specification for "Invisible XML" defines a step called "p:ixml". I wonder if that was intentional?

Most of our steps have longer, more descriptive names. I propose that we should call that step `p:invisible-xml` instead.

Thoughts?

**Comment by xml-project** [comment]
Pro: In XPath the function is called "fn:invisible-xml", so easier to memorize.
Contra: Renaming the step breaks existing pipelines or breaks interoperability if a processor supports the new name exclusively.

**Comment by ndw** [comment]
The existence of the `fn:invisible-xml` function in XPath 4.0 makes me feel very strongly that we should rename the step.

I suggest that we rename it, but note that implementors may wish to recognize `p:ixml` as an alternative for some period of time as it was originally published with that name.

**Comment by gimsieke** [comment]
`p:xslt` (rather than `p:extensible-stylesheet-language-transformation` or the like) is purely acronymic, so there’s precedent. But yes, synchronizing with `fn:invisible-xml` might also be a good idea. I don’t have a strong opinion about it.
