### ISSUE TITLE
Preserved document properties of p:escape-markup

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#75]
Currently for [p:escape-markup](http://spec.xproc.org/master/head/steps/#c.escape-markup) it is said, that no document properties are preserved.

One could understand this step as a special kind of p:insert (which preserves all properties), so I would expected p:escape-markup to do this too. 

Did I miss something?

**Comment by Conal-Tuohy** [comment]
I think a document which is escaped is always an XML document, whereas after unescaping it may be some other type of document (e.g. JSON). Even if it's XML after unescaping, its media type may have changed to something more specific.
