### ISSUE TITLE
p:directory-listing: recursive option; path to match include/exclude filter regexes against

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-steps#76]
Something for Thursday’s hangout in the light of #66:

We should remember what our decisions were (if we arrived at decisions) wrt a) the `recursive` option and b) how the paths look like that are supposed to match `include-filter` and `exclude-filter`.

https://github.com/xproc/Workshop-2018-06/wiki/Minutes#user-content-pdirectory-listing

**Comment by xml-project** [comment]
Reminder: This issue has to be solved together with  #59  and #54

**Comment by ndw** [comment]
This is now part of #89
