### ISSUE TITLE
Clarification in p:namespace-rename required

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#86]
If I did not miss an important thing, we need to say more on p:namespace-rename for the edge case, where a renamed attribute has the same qualified name as an other attribute on the same element.
Example:
````
<p:namespace-rename from="a" to "b">
  <p:with-input>
    <el a:x="5" b:x="6" xmlns:a="a" xmlns:b="b" />
  </p:with-input>
</p:namespace-rename>
````
Both XMLCalabash and MorganaXProc return `<el a:x="6" />`, but `<el: a:x="5" />` if the textual order of attributes is changed. But the [XML specs](https://www.w3.org/TR/REC-xml/#sec-starttags) say, that "the order of attribute specifications in a start-tag or empty-element tag is not significant."

My first impulse would be to say, that the above step should raise an error. But as it was not an error in XProc 1.0 implementations, there are also reason to keep it. But then we have to explain what result is expected without referring to "attribute order".

Opinions?

**Comment by eriksiegel** [comment]
I think raising an error is the right thing to do here. It will be a very edgy case when existing pipelines break on this...
