### ISSUE TITLE
Add p:namespace-delete to standard lib

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#87]
XMLCalabash has an extension step "[cx:namespace-delete](https://xmlcalabash.com/docs/reference/cx-namespace-delete.html)". 
I propose to add this to the standard step library.

Opinion?

**Comment by eriksiegel** [comment]
Good idea. Can we then add the value `#all` (with obvious semantics) as a value for the `name` option?

**Comment by xml-project** [comment]
We decided (05-16 editors call) not to use prefixes to mark the namespaces to be removed, but uris. So the options signature would be xs:anyURI*

**Comment by ndw** [comment]
23 May editor's call; some discussion of the using URIs instead of prefix; @xml-project had persuasive arguements but we can't reconstruct them without him.

**Comment by ndw** [comment]
10 June, consensus is we'll use prefixes and we will make this a standard step.
