### ISSUE TITLE
p:replace needs update due to new document model

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#93]
Currently the [specs](http://spec.xproc.org/master/head/steps/#c.replace) say:

> Every node in the primary input matching the specified pattern is replaced in the output is replaced _by the document element_ of the replacement document.

Since with XProc 3.0 we switched to XDM document, the notion of a "document element" does not make sense any more.

I therefor propose, 

1. that the matched node is replace by all children of the document node of the replacement document. 

2. That a dynamic error is raised, if the resulting document is a text nodes only document (because this step preserves all document properties)

3. To add "text" to `content-types` of port `replacement`.

Could you please give me a GO / NON-GO before I start changing the prose.

**Comment by gimsieke** [comment]
First, “Every node in the primary input matching the specified pattern is replaced in the output is replaced” seems to have a superfluous “is replaced” in it. Not sure which to remove.

Then I’d suggest to replace “document element” with “top-level node(s)”.

I was wondering whether we should say “text or element node(s)” or any node(s). For example, should `p:replace` also be able to replace a placeholder element in the source with a processing instruction? I’m thinking of 

```xml
<p:replace match="/model">
  <p:with-input port="source">
    <p:inline>
      <model/>
      <doc>…</doc>
    </p:inline>
  </p:with-input>
  <p:with-input port="replacement">
    <p:inline>
      <?xml-model …?>
    </p:inline>
  </p:with-input>
```
And if the top-level node(s) of the source document are matched, should the result document carry the document properties of the replacement? 
What if an element is matched and replaced with a text node? Then all document properties cannot be preserved. Or do we say that the content types of source and replacement must match?

**Comment by eriksiegel** [comment]
Would like the "any node(s)" semantics Gerrit proposes.

About replacing the doc properties: No, its a replace and therefore IMHO the original doc is in the lead.

But there are edge cases as Gerrit points out. Not sure... 🤔

**Comment by ndw** [comment]
1. I suppose. If it's not a document element, then I assume the nodes are used as the replacement text.
2. I hope we don't need a new dynamic error for this. I hope we already say somewhere that the output of a step has to match it's content type. That said, I think we allow any XDM to be an application/xml document now, don't we?
3. Sure.

**Comment by ndw** [comment]
23 May editor's call: the p:replace step will have to document that the replacement may change the content-type property of the document. (This might also change the base-uri property.)

**Comment by xml-project** [comment]
I guess this is a general decision which holds also for the same problem on other steps, like p:replace-step where the document node is selected?
